name: Semgrep scan
on:
  pull_request: 
    branches:
      - main
      - master
    paths:
      - .github/workflows/new_cbv.yml

jobs:
  Save new CBV:
    name: Read, format and store new CBV
    runs-on: ubuntu-20.04
    permissions: write-all
    # check that only runs with add cbs request and not with normal code update
    # maybe use standar pull request name to trigger
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v3"

      - name: "Process md"
        run: ./.github/scripts/api.ts # add here any params that are needed